apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: backlog-configmap
    envs:
      - backlog-dev.env

resources:
  - ../../base

commonLabels:
  environment: development
